### ISSUE TITLE
Errors during build and headless execution

### ISSUE THREAD

**Issue by beadyallen** [jeanollion/bacmman#18]
Hi, 

I'm trying to set up BACMMAN to run in headless mode and am hitting two issues. Firstly, the initial build is failing because the "bacmman-blissed" folder is missing during the compile. I can't seem to find any evidence in the git logs of it ever having existed. If I comment out the dependency from bacmman/pom.xml and bacmman/bacmman-ij1_/pom.xml everything seems to build okay but I then hit another problem.

Following the commandline instructions from the wiki I get the following error when trying to run a batch job:

```
xxxx@xxxx:~/BACMMAN_commandline/bacmman/bacmman-headless/target$ java -cp dependency/*:bacmman-headless-3.8.2.jar bacmman.ui.ProcessTasks /media/nba16/febcabea-a9e2-4492-aa64-8f4f1305b18e/20241021_pH_run_processing/BatchProcessing/BATCH_P0.json 
12:23:46.733 [main] INFO  bacmman.plugins.PluginFactory - looking for plugins in package: bacmman.plugins.plugins
12:23:46.899 [main] DEBUG bacmman.plugins.PluginFactory - looking for plugin in package: bacmman.plugins.plugins, path: bacmman/plugins/plugins, #dirs: 0, dirs: [], #classes: 411 10 last : [class bacmman.plugins.plugins.track_post_filter.RemoveTrackByFeature, class bacmman.plugins.plugins.track_post_filter.RemoveTrackByFeature$STAT, class bacmman.plugins.plugins.track_post_filter.RemoveTracksStartingAfterFrame, class bacmman.plugins.plugins.track_post_filter.PostFilter$MERGE_POLICY, class bacmman.plugins.plugins.track_post_filter.PostFilter$DELETE_METHOD, class bacmman.plugins.plugins.track_post_filter.PostFilter, class bacmman.plugins.plugins.track_post_filter.RemoveTrackByFeature$1, class bacmman.plugins.plugins.track_post_filter.TrackLengthFilter, class bacmman.plugins.plugins.track_pre_filters.NormalizeTrack, class bacmman.plugins.plugins.track_pre_filters.PreFilter]
12:23:46.901 [main] INFO  bacmman.plugins.PluginFactory - total plugins found #175
>1 jobs found in file: /media/nba16/febcabea-a9e2-4492-aa64-8f4f1305b18e/20241021_pH_run_processing/BatchProcessing/BATCH_P0.json
>Error @Validation java.lang.IllegalArgumentException: Unsupported DAO type: ObjectBox all types: []
>bacmman.data_structure.MasterDAOFactory.initDAO(MasterDAOFactory.java:93)
>bacmman.data_structure.MasterDAOFactory.getDAO(MasterDAOFactory.java:79)
>bacmman.data_structure.MasterDAOFactory.getDAO(MasterDAOFactory.java:68)
>bacmman.ui.ProcessTasks.main(ProcessTasks.java:88)
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported DAO type: ObjectBox all types: []
        at bacmman.data_structure.MasterDAOFactory.initDAO(MasterDAOFactory.java:93)
        at bacmman.data_structure.MasterDAOFactory.getDAO(MasterDAOFactory.java:79)
        at bacmman.data_structure.MasterDAOFactory.getDAO(MasterDAOFactory.java:68)
        at bacmman.core.Task.initDB(Task.java:523)
        at bacmman.core.Task.countSubtasks(Task.java:729)
        at bacmman.ui.ProcessTasks.main(ProcessTasks.java:96)
```

Any advice for getting this working would be greatly appreciated.

For info I'm running on the follwoing machine:

```
xxxx@xxxx:~/BACMMAN_commandline/bacmman/bacmman-core/target$ lsb_release -a
LSB Version:    core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
xxxx@xxxx:~/BACMMAN_commandline/bacmman/bacmman-core/target$ java -version
openjdk version "1.8.0_432"
OpenJDK Runtime Environment (build 1.8.0_432-8u432-ga~us1-0ubuntu2~22.04-ga)
OpenJDK 64-Bit Server VM (build 25.432-bga, mixed mode)
xxxx@xxx:~/BACMMAN_commandline/bacmman/bacmman-core/target$ 
```

Cheers

Ben

**Comment by jeanollion** [comment]
Hi Ben,
You can safely ignore the module bacmman-blissed, as it has not be released yet.

the issue you are pointing is related to the database (ObjectBox) not being found when you run the command. I think an extra step is needed when you compile but i can't remember, and I'm not available right now. I will try to check that the last week of january.
Best regards,
Jean

15 janv. 2025 07:37:39 Ben Allen ***@***.***>:

**Comment by jeanollion** [comment]
Hi Ben, 
Sorry for the late reply I was away for a long time. 
I have checked your issue, objectbox module was missing in the dependency list. It is fixed now. 
Best
Jean

**Comment by beadyallen** [comment]
Hi Jean,

Not problem. Thanks for the great software. I'd already figured out locally how to get things working anyway. It seems though that there's still an error with the version currently on GitHub - it fails  with DAO errors unless you include a call to MasterDAOFactory.findModules in the ProcessTasks main function:


<pre>
.
.
.
import bacmman.core.Task;
import bacmman.plugins.PluginFactory;
<b>import bacmman.data_structure.MasterDAOFactory;</b>
import bacmman.ui.logger.FileProgressLogger;
.
.
.
public class ProcessTasks {

    public static void main(String[] args) {
        PluginFactory.findPlugins("bacmman.plugins.plugins");
        <b>MasterDAOFactory.findModules("bacmman.data_structure.dao");</b>
        Logger root = (Logger)LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.setLevel(Level.INFO);
        ConsoleProgressLogger consoleUI = new ....

</pre>

I'm definitely not a java programmer so there may be a better way to fix this, but it seems to work for all the headless jobs I've tried.

Thanks

Ben

**Comment by jeanollion** [comment]
Hi Ben, 
yes you are right this is missing. I have not updated this part since a long time. 
 Thanks for your input. 
Replacing `PluginFactory.findPlugins("bacmman.plugins.plugins");` by `Core.getCore();`  should be the solution. 

Best, Jean
